import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import Footer from '../../components/footer/page'
import Header from '../../components/header/page'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ['en', 'uz', 'ru', 'uzb']

export default function RootLayout({ children,  params: {locale} }) {

  const messages = useMessages()
  
  if(!locales.includes(locale)){
    notFound()
  }


  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body suppressHydrationWarning={true} className={inter.className}>
            <Header locale={locale} />
            {children}
            <Footer/>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
